# Generated by Django 2.2 on 2020-06-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_custom', '0003_auto_20200622_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=None),
        ),
        migrations.RemoveField(
            model_name='ejemplar',
            name='libro',
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ManyToManyField(to='biblioteca_custom.Libro'),
        ),
    ]
