# Generated by Django 2.2 on 2020-06-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_custom', '0005_auto_20200622_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
