# Generated by Django 2.2 on 2020-06-22 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_custom', '0006_auto_20200622_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='libro',
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca_custom.Libro'),
        ),
    ]
