# Generated by Django 2.2 on 2020-06-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_custom', '0008_auto_20200622_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
