# Generated by Django 2.2 on 2020-06-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=25)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('documento', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(default=None, max_length=35)),
                ('ejemplar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca_custom.Ejemplar')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=20)),
                ('paginas', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_custom.Autor')),
            ],
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca_custom.Libro'),
        ),
    ]
