# Generated by Django 2.2 on 2020-06-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
