# Generated by Django 2.2 on 2020-07-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(to='tienda.Producto'),
        ),
    ]
