# Generated by Django 2.2 on 2020-06-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20200625_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
