# Generated by Django 2.2 on 2020-07-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20200702_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto'),
        ),
    ]
