# Generated by Django 2.2 on 2020-07-02 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20200702_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.Proveedor'),
        ),
    ]
