# Generated by Django 2.2 on 2020-07-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_venta_desc_apl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='desc_apl',
        ),
    ]
