# Generated by Django 2.2 on 2020-07-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_venta_desc_apl'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='desc_apl',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
