# Generated by Django 2.2 on 2020-07-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_venta_desc_apl'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
