# Generated by Django 2.2 on 2020-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_venta_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.IntegerField(),
        ),
    ]
