# Generated by Django 2.2 on 2020-07-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20200702_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='desc_apl',
            field=models.BooleanField(default=False),
        ),
    ]
