# Generated by Django 2.2 on 2020-07-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_auto_20200702_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='desc_apl',
            new_name='apl_desc',
        ),
    ]
